version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - my_db_data:/var/lib/mysql
##      - ./init.sql:/data/application/init.sql
    restart: always
##    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer
      MYSQL_USER: ankit
      MYSQL_PASSWORD: ankit

volumes:
  my_db_data: {}
