apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  namespace: ans
  labels:
    env: dev
    role: web
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
